# Generated by Django 5.0.2 on 2024-03-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptn', '0002_contact_password_alter_contact_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iname', models.CharField(max_length=100)),
                ('ipassword', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
