# Generated by Django 5.0.2 on 2024-03-19 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptn', '0003_insta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Insta',
            new_name='Inst',
        ),
    ]
